const DECREASE ="DECREASE";
const INCREASE ="INCREASE";
const REMOVE ="REMOVE";
const GET_TOTAL ="GET_TOTAL";
const CLEAR_CART ="CLEAR_CART"
const GET_AMOUNT="GET_AMOUNT"


export{DECREASE,INCREASE,REMOVE,GET_TOTAL,CLEAR_CART,GET_AMOUNT}